# Generated by Django 5.1.3 on 2024-11-29 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_group_quota_alter_group_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
