# Generated by Django 5.1.3 on 2024-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_group_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
