# Generated by Django 5.1.3 on 2024-12-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_announcement_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='cover',
        ),
    ]
